version: '3'
services:

  db:
    image: postgres
    hostname: db_base
    restart: always
    environment:
      POSTGRES_PASSWORD: Z)<f[>sOXXcBJ>wi
    volumes:
      - pgdata:/var/lib/postgresql/data/
  
  # redis:
  #   image: redis
  #   container_name: redis
  #   hostname: redis
  #   restart: always
  #   volumes:
  #     - redisdata:/data

  nginx:
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:rw
      - ./frontend/dist:/frontend/dist/
      - static_volume:/backend/static
      - media_volume:/backend/media
    depends_on:
      - backend

  backend:
      build: ./backend
      command: "gunicorn --chdir backend --bind :8000 backend.wsgi:application" 
      restart: always
      volumes:
        - .:/backend
        - static_volume:/backend/static
        - media_volume:/backend/media
      links:
        - db
        # - redis
      depends_on:
        - db
        # - redis

volumes:
  pgdata:
  # redisdata:
  static_volume:
  media_volume: