# Generated by Django 3.0 on 2019-12-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Driver', 'Driver'), ('Operator', 'Operator'), ('Accounting', 'Accounting')], default='Customer', max_length=16),
        ),
    ]
