# Generated by Django 2.2 on 2019-12-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('view', 'Can view user'), ('add', 'Can add user'), ('change', 'Can change user'), ('delete', 'Can delete user'), ('export', 'Can export user'))},
        ),
    ]
