# Generated by Django 3.0 on 2019-12-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191216_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Driver'), (3, 'Operator'), (4, 'Accounting')], default=1),
        ),
    ]
