# Generated by Django 3.0 on 2019-12-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organization',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
