# Generated by Django 3.0 on 2019-12-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
