# Generated by Django 3.0 on 2019-12-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model',
            field=models.IntegerField(choices=[(5, 'Car'), (11, 'Bus')], default=11),
        ),
    ]
