# Generated by Django 3.0 on 2019-12-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20191223_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='supplier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
