# Generated by Django 3.0 on 2019-12-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'itinerary',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('New', 'Created'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Complete', 'Complete')], default='New', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
