# Generated by Django 3.0 on 2019-12-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitinerary',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
