# Generated by Django 3.0 on 2019-12-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191216_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary', to='order.Order'),
        ),
    ]
