# Generated by Django 3.0 on 2019-12-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191230_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitinerary',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
