# Generated by Django 3.0 on 2019-12-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitinerary_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitinerary',
            options={'permissions': [('change_payment', 'Can change the payment')]},
        ),
    ]
