# Generated by Django 3.0 on 2019-12-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191223_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
