# Generated by Django 3.0 on 2020-01-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200109_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirm', 'Confirm'), ('Cancel', 'Cancel')], default='New', max_length=16),
        ),
    ]
