# Generated by Django 3.0 on 2019-12-31 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191231_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitinerary',
            options={'permissions': [('edit_payment', 'Can change the payment')]},
        ),
    ]
