# Generated by Django 3.0 on 2019-12-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='seats',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
