# Generated by Django 3.0 on 2019-12-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191231_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitinerary',
            options={'permissions': [('edit_payment', 'Can edit the payment')]},
        ),
    ]
