# Generated by Django 3.0 on 2019-12-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191225_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Complete', 'Complete')], default='New', max_length=16),
        ),
    ]
