# Generated by Django 3.0 on 2019-12-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191231_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitinerary',
            options={'permissions': [('edit_payment', 'Can edit the payment'), ('change_status', 'Can change the status')]},
        ),
    ]
