# Generated by Django 3.0 on 2019-12-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191226_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='passenger',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
