# Generated by Django 3.0 on 2019-12-31 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191231_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitinerary',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_itinerary', to='order.Order'),
        ),
    ]
