# Generated by Django 3.0 on 2019-12-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
