# Generated by Django 3.0 on 2019-12-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20191228_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirm', 'Confirm'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Complete', 'Complete')], default='New', max_length=16),
        ),
    ]
