# Generated by Django 3.0 on 2019-12-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191229_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vehicl_id',
            new_name='vehicle_id',
        ),
    ]
