# Generated by Django 3.0 on 2020-01-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200101_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitinerary',
            options={'permissions': [('edit_payment', 'Can edit the payment'), ('change_lock', 'Can change the lock')]},
        ),
    ]
