# Generated by Django 3.0 on 2020-01-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200101_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('change_lock', 'Can change the lock')]},
        ),
        migrations.AlterModelOptions(
            name='orderitinerary',
            options={'permissions': [('edit_payment', 'Can edit the payment')]},
        ),
    ]
