# Generated by Django 3.0 on 2019-12-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191230_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='order',
            name='vehicl_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
