# Generated by Django 3.0 on 2019-12-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20191230_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vehicl_id',
            new_name='vehicle_id',
        ),
    ]
